name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PythonAnywhere CLI
        run: |
          python3 -m pip install --upgrade --force-reinstall pythonanywhere --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Login and deploy
        env:
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          pythonanywhere login --apikey $PYTHONANYWHERE_API_TOKEN
          pythonanywhere run "cd ~/mysite && git pull"
          pythonanywhere webapp reload Moejoe06.pythonanywhere.com
