name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to PythonAnywhere
        env:
          PYTHONANYWHERE_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          # Install CLI for the current user
          python3 -m pip install --upgrade --force-reinstall pythonanywhere --user
          
          # Add the CLI to PATH so the shell can find it
          export PATH=$HOME/.local/bin:$PATH
          
          # Now run commands
          pythonanywhere login --apikey $PYTHONANYWHERE_API_TOKEN
          pythonanywhere run "cd ~/mysite && git pull"
          pythonanywhere webapp reload Moejoe06.pythonanywhere.com
